export interface Category {
  id: string
  name: string
  slug: string
}

export interface Book {
  id: string
  title: string
  author: string
  translator: string | null
  publisher: string
  isbn: string
  page_count: number
  price: number
  category_id: string
  category_name: string
  cover_image: string
  synopsis: string
  preview_pdf_url: string
  created_at: string
  stock: number
  weight: number
  dimensions: string
  language: string
  publication_year: number
}

export const categories: Category[] = [
  { id: "1", name: "Aqidah & Tauhid", slug: "aqidah-tauhid" },
  { id: "2", name: "Fiqih & Ibadah", slug: "fiqih-ibadah" },
  { id: "3", name: "Tafsir & Ulumul Qur'an", slug: "tafsir-quran" },
  { id: "4", name: "Hadits & Musthalah", slug: "hadits-musthalah" },
  { id: "5", name: "Tasawuf & Akhlaq", slug: "tasawuf-akhlaq" },
  { id: "6", name: "Sejarah & Biografi", slug: "sejarah-biografi" },
  { id: "7", name: "Bahasa & Sastra Arab", slug: "bahasa-arab" },
  { id: "8", name: "Buku Anak & Keluarga", slug: "buku-anak" },
]

export const books: Book[] = [
  {
    id: "bk-001",
    title: "Mukhtashar Shahih al-Bukhari",
    author: "Imam al-Bukhari",
    translator: "M. Nashiruddin al-Albani",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-1",
    page_count: 720,
    price: 145000,
    category_id: "4",
    category_name: "Hadits & Musthalah",
    cover_image: "/images/books/bukhari.jpg",
    synopsis: "Ringkasan Shahih al-Bukhari yang memuat hadits-hadits pilihan untuk memudahkan kaum muslimin dalam mempelajari sunnah Nabi. Disusun dengan sistematika yang rapi dan dilengkapi takhrij singkat.",
    preview_pdf_url: "/preview/mukhtashar-bukhari.pdf",
    created_at: "2025-01-10T00:00:00.000Z",
    stock: 50,
    weight: 850,
    dimensions: "17 x 24 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-002",
    title: "Syarah Ushul Tsalatsah",
    author: "Syaikh Muhammad bin Abdul Wahhab",
    translator: "Abu Haidar as-Sundawy",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-2",
    page_count: 280,
    price: 65000,
    category_id: "1",
    category_name: "Aqidah & Tauhid",
    cover_image: "/images/books/ushul-tsalatsah.jpg",
    synopsis: "Penjelasan mendalam tentang tiga landasan utama dalam agama Islam yang wajib diketahui setiap muslim. Dilengkapi dengan dalil-dalil dari al-Qur'an dan as-Sunnah.",
    preview_pdf_url: "/preview/syarah-ushul-tsalatsah.pdf",
    created_at: "2025-02-15T00:00:00.000Z",
    stock: 75,
    weight: 350,
    dimensions: "14 x 20 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-003",
    title: "Taysir al-Karim ar-Rahman: Tafsir Surat Pilihan",
    author: "Syaikh Abdurrahman as-Sa'di",
    translator: "Tim Penerjemah Maktabah al-Mughis",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-3",
    page_count: 520,
    price: 120000,
    category_id: "3",
    category_name: "Tafsir & Ulumul Qur'an",
    cover_image: "/images/books/tafsir-sadi.jpg",
    synopsis: "Tafsir ringkas namun padat dari surat-surat pilihan dalam al-Qur'an. Gaya bahasa yang mudah dipahami menjadikan tafsir ini cocok untuk semua kalangan.",
    preview_pdf_url: "/preview/tafsir-sadi.pdf",
    created_at: "2025-03-05T00:00:00.000Z",
    stock: 40,
    weight: 650,
    dimensions: "16 x 24 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-004",
    title: "Panduan Shalat Lengkap Sesuai Sunnah",
    author: "Syaikh Muhammad Nashiruddin al-Albani",
    translator: "Abu Umar al-Mughisi",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-4",
    page_count: 320,
    price: 78000,
    category_id: "2",
    category_name: "Fiqih & Ibadah",
    cover_image: "/images/books/panduan-shalat.jpg",
    synopsis: "Buku panduan shalat praktis yang disusun berdasarkan dalil-dalil shahih. Mulai dari thaharah hingga salam, dilengkapi dengan ilustrasi dan tata cara yang benar.",
    preview_pdf_url: "/preview/panduan-shalat.pdf",
    created_at: "2025-03-20T00:00:00.000Z",
    stock: 100,
    weight: 400,
    dimensions: "15 x 21 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-005",
    title: "Al-Wafi: Syarah Hadits Arba'in",
    author: "Syaikh Musthafa al-'Adawi",
    translator: "Abdullah Haidir",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-5",
    page_count: 450,
    price: 99000,
    category_id: "4",
    category_name: "Hadits & Musthalah",
    cover_image: "/images/books/al-wafi.jpg",
    synopsis: "Syarah lengkap 42 hadits inti dalam agama Islam. Setiap hadits dijelaskan maknanya, faedahnya, dan aplikasinya dalam kehidupan sehari-hari.",
    preview_pdf_url: "/preview/al-wafi.pdf",
    created_at: "2025-04-01T00:00:00.000Z",
    stock: 60,
    weight: 500,
    dimensions: "16 x 23 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-006",
    title: "Membentuk Pribadi Muslim Ideal",
    author: "Syaikh Muhammad al-Munajjid",
    translator: "Ahmad Fauzi",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-6",
    page_count: 360,
    price: 85000,
    category_id: "5",
    category_name: "Tasawuf & Akhlaq",
    cover_image: "/images/books/pribadi-muslim.jpg",
    synopsis: "Panduan praktis membentuk kepribadian muslim yang ideal berdasarkan al-Qur'an dan as-Sunnah. Membahas akhlaq terhadap Allah, sesama, dan lingkungan.",
    preview_pdf_url: "/preview/pribadi-muslim.pdf",
    created_at: "2025-04-15T00:00:00.000Z",
    stock: 55,
    weight: 420,
    dimensions: "15 x 22 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-007",
    title: "Sirah Nabawiyah untuk Pemula",
    author: "Dr. Shalih al-Maghamisi",
    translator: "Tim Penerjemah Maktabah al-Mughis",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-7",
    page_count: 280,
    price: 72000,
    category_id: "6",
    category_name: "Sejarah & Biografi",
    cover_image: "/images/books/sirah-nabawiyah.jpg",
    synopsis: "Biografi ringkas Rasulullah shallallahu 'alaihi wa sallam yang disajikan dengan bahasa populer. Cocok untuk pembaca awam yang ingin mengenal sejarah hidup Nabi.",
    preview_pdf_url: "/preview/sirah-nabawiyah.pdf",
    created_at: "2025-05-01T00:00:00.000Z",
    stock: 80,
    weight: 330,
    dimensions: "14 x 20 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-008",
    title: "Belajar Bahasa Arab Metode Al-Mughis",
    author: "Ustadz Abu Zakaria al-Mughisi",
    translator: null,
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-8",
    page_count: 200,
    price: 55000,
    category_id: "7",
    category_name: "Bahasa & Sastra Arab",
    cover_image: "/images/books/belajar-arab.jpg",
    synopsis: "Metode praktis belajar bahasa Arab untuk pemula. Disusun dengan pendekatan tematik dan dilengkapi dengan latihan-latihan yang memudahkan pemahaman.",
    preview_pdf_url: "/preview/belajar-arab.pdf",
    created_at: "2025-05-15T00:00:00.000Z",
    stock: 90,
    weight: 250,
    dimensions: "14 x 20 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-009",
    title: "Aku Cinta Allah: Cerita untuk Anak Muslim",
    author: "Ummu Ihsan",
    translator: null,
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-01-9",
    page_count: 64,
    price: 35000,
    category_id: "8",
    category_name: "Buku Anak & Keluarga",
    cover_image: "/images/books/aku-cinta-allah.jpg",
    synopsis: "Buku cerita bergambar yang mengajarkan anak-anak tentang kecintaan kepada Allah melalui kisah-kisah sehari-hari yang penuh hikmah.",
    preview_pdf_url: "/preview/aku-cinta-allah.pdf",
    created_at: "2025-06-01T00:00:00.000Z",
    stock: 120,
    weight: 150,
    dimensions: "18 x 18 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-010",
    title: "Al-Qawa'id al-Fiqhiyyah",
    author: "Syaikh Abdul Majid Turkmani",
    translator: "Dr. Ahmad Zainuddin",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-0",
    page_count: 380,
    price: 95000,
    category_id: "2",
    category_name: "Fiqih & Ibadah",
    cover_image: "/images/books/qawaid-fiqhiyyah.jpg",
    synopsis: "Kumpulan kaidah-kaidah fiqih yang memudahkan dalam memahami hukum-hukum Islam. Dilengkapi dengan contoh aplikasi dan penjelasan yang sistematis.",
    preview_pdf_url: "/preview/qawaid-fiqhiyyah.pdf",
    created_at: "2025-06-10T00:00:00.000Z",
    stock: 45,
    weight: 480,
    dimensions: "16 x 23 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-011",
    title: "Tazkiyatun Nafs: Mensucikan Jiwa",
    author: "Syaikh Ahmad Farid",
    translator: "Abu Hasan al-Mughisi",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-1",
    page_count: 420,
    price: 98000,
    category_id: "5",
    category_name: "Tasawuf & Akhlaq",
    cover_image: "/images/books/tazkiyatun-nafs.jpg",
    synopsis: "Panduan lengkap dalam membersihkan jiwa dari penyakit-penyakit hati berdasarkan al-Qur'an dan as-Sunnah. Disertai dengan dzikir dan amalan-amalan hati.",
    preview_pdf_url: "/preview/tazkiyatun-nafs.pdf",
    created_at: "2025-06-20T00:00:00.000Z",
    stock: 35,
    weight: 510,
    dimensions: "16 x 24 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-012",
    title: "Kisah Para Nabi untuk Remaja",
    author: "Abu Hafsh al-Mughisi",
    translator: null,
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-2",
    page_count: 180,
    price: 48000,
    category_id: "6",
    category_name: "Sejarah & Biografi",
    cover_image: "/images/books/kisah-nabi.jpg",
    synopsis: "Kisah-kisah para nabi yang disajikan khusus untuk remaja muslim. Bahasa yang ringan dan penuh hikmah untuk membangun karakter islami sejak dini.",
    preview_pdf_url: "/preview/kisah-nabi.pdf",
    created_at: "2025-07-01T00:00:00.000Z",
    stock: 70,
    weight: 200,
    dimensions: "14 x 20 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-013",
    title: "Jami' al-'Ulum wa al-Hikam",
    author: "Ibnu Rajab al-Hanbali",
    translator: "Dr. Muhammad Nur Ihsan",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-3",
    page_count: 650,
    price: 155000,
    category_id: "4",
    category_name: "Hadits & Musthalah",
    cover_image: "/images/books/jami-ulum.jpg",
    synopsis: "Syarah 50 hadits inti yang mencakup seluruh ajaran Islam. Kitab klasik yang menjadi rujukan penting dalam memahami intisari agama.",
    preview_pdf_url: "/preview/jami-ulum.pdf",
    created_at: "2025-07-10T00:00:00.000Z",
    stock: 25,
    weight: 780,
    dimensions: "17 x 25 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-014",
    title: "Mudah Menghafal al-Qur'an",
    author: "Ustadz Abu Yahya al-Mughisi",
    translator: null,
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-4",
    page_count: 160,
    price: 45000,
    category_id: "3",
    category_name: "Tafsir & Ulumul Qur'an",
    cover_image: "/images/books/hafal-quran.jpg",
    synopsis: "Metode praktis dan terbukti dalam menghafal al-Qur'an. Dilengkapi dengan tips menghafal, manajemen waktu, dan cara mempertahankan hafalan.",
    preview_pdf_url: "/preview/hafal-quran.pdf",
    created_at: "2025-07-15T00:00:00.000Z",
    stock: 65,
    weight: 200,
    dimensions: "13 x 19 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-015",
    title: "Adab Sehari-Hari Muslim",
    author: "Syaikh Abdul Aziz bin Baz",
    translator: "Tim Penerjemah Maktabah al-Mughis",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-5",
    page_count: 240,
    price: 59000,
    category_id: "5",
    category_name: "Tasawuf & Akhlaq",
    cover_image: "/images/books/adab-sehari.jpg",
    synopsis: "Buku saku yang membahas adab-adab islami dalam kehidupan sehari-hari. Mulai dari adab makan, tidur, berpakaian, hingga bergaul dengan sesama.",
    preview_pdf_url: "/preview/adab-sehari.pdf",
    created_at: "2025-08-01T00:00:00.000Z",
    stock: 85,
    weight: 280,
    dimensions: "13 x 19 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-016",
    title: "Nahwu untuk Pemula",
    author: "Ustadz Abu Umar al-Mughisi",
    translator: null,
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-6",
    page_count: 220,
    price: 52000,
    category_id: "7",
    category_name: "Bahasa & Sastra Arab",
    cover_image: "/images/books/nahwu-pemula.jpg",
    synopsis: "Belajar ilmu nahwu dengan metode yang mudah dipahami. Disusun secara bertahap dari dasar hingga tingkat lanjutan dengan contoh-contoh aplikatif.",
    preview_pdf_url: "/preview/nahwu-pemula.pdf",
    created_at: "2025-08-15T00:00:00.000Z",
    stock: 95,
    weight: 270,
    dimensions: "14 x 20 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-017",
    title: "Mutiara Nasihat untuk Wanita Muslimah",
    author: "Ummu Abdillah",
    translator: null,
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-7",
    page_count: 190,
    price: 55000,
    category_id: "8",
    category_name: "Buku Anak & Keluarga",
    cover_image: "/images/books/mutiara-wanita.jpg",
    synopsis: "Kumpulan nasihat dan bimbingan untuk wanita muslimah dalam menjalani perannya sebagai hamba Allah, istri, ibu, dan anggota masyarakat.",
    preview_pdf_url: "/preview/mutiara-wanita.pdf",
    created_at: "2025-08-20T00:00:00.000Z",
    stock: 110,
    weight: 230,
    dimensions: "14 x 20 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-018",
    title: "Al-Mughis: Ensiklopedia Do'a",
    author: "Tim Ulama Maktabah al-Mughis",
    translator: null,
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-8",
    page_count: 480,
    price: 110000,
    category_id: "1",
    category_name: "Aqidah & Tauhid",
    cover_image: "/images/books/ensiklopedia-doa.jpg",
    synopsis: "Kumpulan do'a-do'a dari al-Qur'an dan as-Sunnah yang disusun berdasarkan tema. Dilengkapi dengan transliterasi, arti, dan penjelasan singkat.",
    preview_pdf_url: "/preview/ensiklopedia-doa.pdf",
    created_at: "2025-09-01T00:00:00.000Z",
    stock: 30,
    weight: 580,
    dimensions: "16 x 24 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-019",
    title: "Manhaj Ahlus Sunnah dalam Berakidah",
    author: "Syaikh Shalih Fauzan",
    translator: "Abu Abdillah al-Mughisi",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-02-9",
    page_count: 310,
    price: 75000,
    category_id: "1",
    category_name: "Aqidah & Tauhid",
    cover_image: "/images/books/manhaj-aqidah.jpg",
    synopsis: "Penjelasan tentang manhaj Ahlus Sunnah wal Jama'ah dalam memahami dan mengamalkan aqidah Islamiyah. Rujukan penting bagi penuntut ilmu.",
    preview_pdf_url: "/preview/manhaj-aqidah.pdf",
    created_at: "2025-09-10T00:00:00.000Z",
    stock: 40,
    weight: 380,
    dimensions: "15 x 21 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
  {
    id: "bk-020",
    title: "Pendidikan Anak dalam Islam",
    author: "Syaikh Abdullah Nashih 'Ulwan",
    translator: "Dr. Ahmad al-Mughisi",
    publisher: "Maktabah al-Mughis",
    isbn: "978-602-XXXX-03-0",
    page_count: 550,
    price: 130000,
    category_id: "8",
    category_name: "Buku Anak & Keluarga",
    cover_image: "/images/books/pendidikan-anak.jpg",
    synopsis: "Panduan komprehensif dalam mendidik anak sesuai tuntunan Islam. Membahas pendidikan iman, akhlaq, fisik, intelektual, dan sosial anak.",
    preview_pdf_url: "/preview/pendidikan-anak.pdf",
    created_at: "2025-09-20T00:00:00.000Z",
    stock: 20,
    weight: 680,
    dimensions: "17 x 24 cm",
    language: "Indonesia",
    publication_year: 2025,
  },
]
