export interface BlogArticle {
  id: string
  slug: string
  title: string
  excerpt: string
  category: string
  author: string
  authorRole: string
  publishedAt: string
  readingTime: string
  coverGradient: string
  featured: boolean
}

export const categories = [
  "Semua",
  "Penerbitan",
  "Percetakan",
  "ISBN",
  "Menulis",
  "Tips",
  "Berita",
] as const

export const blogArticles: BlogArticle[] = [
  {
    id: "1",
    slug: "panduan-lengkap-menerbitkan-buku",
    title: "Panduan Lengkap Menerbitkan Buku untuk Penulis Pemula",
    excerpt: "Ingin menerbitkan buku tapi bingung harus mulai dari mana? Simak panduan langkah demi langkah menerbitkan buku secara profesional dari naskah hingga distribusi.",
    category: "Penerbitan",
    author: "Tim Mughis",
    authorRole: "Tim Penerbitan",
    publishedAt: "15 Juli 2026",
    readingTime: "8 menit",
    coverGradient: "from-emerald-600 to-teal-700",
    featured: true,
  },
  {
    id: "2",
    slug: "mengenal-isbn-fungsi-dan-biaya",
    title: "Mengenal ISBN: Fungsi, Cara Mendapatkan, dan Biayanya",
    excerpt: "ISBN adalah elemen penting dalam dunia penerbitan. Pelajari apa itu ISBN, fungsinya, dan bagaimana cara mendapatkannya untuk buku Anda.",
    category: "ISBN",
    author: "Tim Mughis",
    authorRole: "Tim ISBN",
    publishedAt: "12 Juli 2026",
    readingTime: "6 menit",
    coverGradient: "from-blue-600 to-indigo-700",
    featured: false,
  },
  {
    id: "3",
    slug: "tips-menulis-buku-disukai-penerbit",
    title: "7 Tips Menulis Buku yang Disukai Penerbit",
    excerpt: "Tidak semua naskah lolos kurasi penerbit. Pelajari tujuh tips menulis yang akan membuat naskah Anda lebih menarik di mata penerbit profesional.",
    category: "Menulis",
    author: "Ahmad Rizki",
    authorRole: "Editor Senior",
    publishedAt: "10 Juli 2026",
    readingTime: "5 menit",
    coverGradient: "from-violet-600 to-purple-700",
    featured: false,
  },
  {
    id: "4",
    slug: "proses-cetak-buku-dari-naskah",
    title: "Proses Cetak Buku: Dari Naskah hingga Menjadi Buku Fisik",
    excerpt: "Bagaimana sebuah naskah digital berubah menjadi buku fisik yang siap dibaca? Ikuti perjalanan lengkapnya di percetakan modern.",
    category: "Percetakan",
    author: "Tim Mughis",
    authorRole: "Tim Produksi",
    publishedAt: "8 Juli 2026",
    readingTime: "7 menit",
    coverGradient: "from-gold to-gold-dark",
    featured: false,
  },
  {
    id: "5",
    slug: "perbedaan-penerbit-mayor-indie-self-publishing",
    title: "Penerbit Mayor, Indie, atau Self-Publishing? Pilih yang Tepat",
    excerpt: "Masing-masing jalur penerbitan punya kelebihan dan kekurangan. Temukan mana yang paling sesuai dengan kebutuhan dan tujuan buku Anda.",
    category: "Penerbitan",
    author: "Siti Nurhaliza",
    authorRole: "Konsultan Penerbitan",
    publishedAt: "5 Juli 2026",
    readingTime: "10 menit",
    coverGradient: "from-rose-600 to-pink-700",
    featured: false,
  },
  {
    id: "6",
    slug: "cara-mendaftarkan-haki-buku",
    title: "Cara Mendaftarkan Hak Cipta (HAKI) untuk Buku",
    excerpt: "Lindungi karya intelektual Anda dengan mendaftarkan hak cipta. Simak prosedur lengkap dan persyaratannya di sini.",
    category: "ISBN",
    author: "Tim Mughis",
    authorRole: "Tim Legal",
    publishedAt: "3 Juli 2026",
    readingTime: "4 menit",
    coverGradient: "from-cyan-600 to-sky-700",
    featured: false,
  },
  {
    id: "7",
    slug: "inspirasi-menulis-dari-pengalaman-sehari-hari",
    title: "Inspirasi Menulis Buku dari Pengalaman Sehari-hari",
    excerpt: "Tidak perlu jadi penulis profesional untuk menulis buku. Temukan inspirasi dari hal-hal sederhana di sekitar Anda.",
    category: "Menulis",
    author: "Ahmad Rizki",
    authorRole: "Editor Senior",
    publishedAt: "1 Juli 2026",
    readingTime: "5 menit",
    coverGradient: "from-fuchsia-600 to-pink-700",
    featured: false,
  },
  {
    id: "8",
    slug: "keuntungan-menerbitkan-buku-profesional",
    title: "5 Keuntungan Menerbitkan Buku Secara Profesional",
    excerpt: "Apa saja manfaat yang bisa Anda dapatkan dengan menerbitkan buku melalui penerbit profesional? Simak ulasan lengkapnya.",
    category: "Penerbitan",
    author: "Tim Mughis",
    authorRole: "Tim Penerbitan",
    publishedAt: "28 Juni 2026",
    readingTime: "6 menit",
    coverGradient: "from-lime-600 to-green-700",
    featured: false,
  },
  {
    id: "9",
    slug: "tips-memilih-kertas-cetak-buku",
    title: "Tips Memilih Jenis Kertas yang Tepat untuk Cetak Buku",
    excerpt: "Pemilihan kertas sangat mempengaruhi kualitas dan kenyamanan membaca buku. Pelajari jenis-jenis kertas dan kegunaannya.",
    category: "Percetakan",
    author: "Tim Mughis",
    authorRole: "Tim Produksi",
    publishedAt: "25 Juni 2026",
    readingTime: "7 menit",
    coverGradient: "from-stone-600 to-zinc-700",
    featured: false,
  },
  {
    id: "10",
    slug: "berita-mughis-raih-penghargaan",
    title: "PT Mughis Cipta Media Raih Penghargaan Penerbit Terbaik 2026",
    excerpt: "Penghargaan ini diberikan atas dedikasi dan inovasi dalam industri penerbitan buku nasional selama setahun terakhir.",
    category: "Berita",
    author: "Tim Mughis",
    authorRole: "Tim Humas",
    publishedAt: "20 Juni 2026",
    readingTime: "3 menit",
    coverGradient: "from-gold-light to-gold",
    featured: false,
  },
]
